version: '3.1'
services:
    mongodb:
      image: vstharani8/mongodb:1.0
      container_name: mongodb
      volumes:
        - /data:/data/db
      ports:
        - 27017:27017
      restart: always


    app:
      depends_on:
        - mongodb
      image: vstharani8/restaurant:1.0
      container_name: restaurant
      ports:
        - "8080:8080"
      restart: always
      environment:
        MONGO_URI: mongodb://mongodb:27017/restaurant