apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: vstharani8/app:1.0
          env:
          - name: MONGO_URI
            value: mongodb://mongo:27017/restaurant
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
